project:
  type: website

website:
  title: "இலண்டன் திருக்குறள் பள்ளி"
  navbar:
      background: primary
      search: true
      left:
        - text: "Home"
          file: index.qmd
        - sidebar:batch1
        - sidebar:batch2
        - sidebar:batch3
        - sidebar:summer

  sidebar:
  - id: batch1
    title: "Batch 1"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - batch1.qmd
      - homework-batch1.qmd
  
  - id: batch2
    title: "Batch 2"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - batch2.qmd

  - id: batch3
    title: "Batch 3"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - batch3.qmd

  - id: summer
    title: "Summer 2024"
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - Summer.qmd

comments:
  giscus:
    repo: "thelondonschoolofthirukkural/thelondonschoolofthirukkural.github.io"
    repo-id: "R_kgDOKgZPFA"
    category: "Announcements"
    category-id: "DIC_kwDOKgZPFM4CaIuq"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "bottom"
    theme: "dark"
    loading: "lazy"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



